### ISSUE TITLE
[QUESTION]: Is there / will be there a plugin developement API / sdk / framework / specification for this project?

### ISSUE THREAD

**Issue by Paillat-dev** [AutoPackAI/beebot#14]
I think the title is clear enough but feel free to ask if you don't understand.

**Comment by erik-megarad** [comment]
Right now there isn't much, but I am currently doing a refactor which should allow this. It will allow customized sub-agents which can receive and process subtasks. This should allow you to do almost anything.

I'll update this thread when I've got it done.
