### ISSUE TITLE
.env template says beebot uses gpt4 or 3.5-turbo but actually uses 3.5-turbo-16k

### ISSUE THREAD

**Issue by NeonN3mesis** [AutoPackAI/beebot#5]
![image](https://github.com/AutoPackAI/beebot/assets/129052650/9bd73f82-1b82-4450-8bcb-2f63f22107a6)
Helicone
![image](https://github.com/AutoPackAI/beebot/assets/129052650/a48341d0-b89d-47b9-8ec4-e290b249fa61)

**Comment by erik-megarad** [comment]
Nice, ty, fixed in 3b272534725c65c6d6501244ee78959219e1430e
